### ISSUE TITLE
Ingress & PriorityClass versions are not compatible with k8s 1.13

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#106]
Using current master. I'm running with the following versions:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Using a values file for my settings:

```
webHandlers:
  replicaCount: 3

jobHandlers:
  replicaCount: 1

persistence:
  existingClaim: galaxy-pvc-nfs

service:
  type: NodePort
  port: 30700
```

On the values file I have additional configs for galaxy.yaml, but I doubt that they would have any impact.

When executing inside the galaxy directory:

```
helm install --values galaxy-config-helmv3.yaml .
```

I get:

```
Error: validation failed: [unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1", unable to recognize "": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1"]
```

Thanks!

**Comment by pcm32** [comment]
Ok, Ingress moved to `v1beta1 networking.k8s.io` on 1.14, so documentation is wrong and 1.13 is no longer supported.

**Comment by pcm32** [comment]
PriorityClass move to v1 on 1.15. So, question is, do we really need to move forward on these two to leave 1.13 behind? 

PriorityClass v1beta1 would allow backward compatibility to 1.13. 
Ingress v1beta1 extensions would allow backward compatibility to 1.13.

**Comment by pcm32** [comment]
Ingress was changed of version here: https://github.com/galaxyproject/galaxy-helm/commit/d3b0317341b79a4c56d3ca1478b11d50849b59ec#diff-3c8c73dd3591f76316dd67ad252b85a8L5 

Did the annotation require it?

PriorityClass was first used here: https://github.com/galaxyproject/galaxy-helm/commit/bbea6846d3c8dce2b262d9683a22a27e70dc66aa#diff-16cf5ea7ab499aa6c466886c0df38794

Would it be feasible to use an older version?

**Comment by pcm32** [comment]
@nuwang would you be happy to revert the mentioned versions of the API objects for backward compatibility? Thanks

**Comment by pcm32** [comment]
Making those changes allows the setup to be deployed on 1.13 :-).

**Comment by almahmoud** [comment]
If you already have the changes, could you push a quick PR with them?
I can test with Helm 3 and K8S 1.17, and if nothing breaks I'd vote we can go ahead and change them to be backwards compatible as long as possible.

**Comment by pcm32** [comment]
Sure, will do!

**Comment by almahmoud** [comment]
Closing with the merged PR. Thank you for this!

**Comment by nathanweeks** [comment]
It seems that galaxy/templates/priorityclass-job.yaml  isn't compatible with k8s before v1.15, as sets preemptionPolicy, which wasn't added to PriorityClass until k8s v1.15.

**Comment by pcm32** [comment]
Thanks for reporting that. We were thinking on adding some conditionality to be able to enable certain things or not based on k8s version.

**Comment by pcm32** [comment]
What is the error that you're getting, I think I was deploying on 1.14 on GKE last week with the latest version and didn't get errors... but I might be wrong in the GKE version. Thanks.

**Comment by pcm32** [comment]
yes, 1.14.10-gke27....

**Comment by nathanweeks** [comment]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
$ git rev-parse HEAD
1bbe7e51a076df501f5be35e3c838d3ee485bf01
$ helm install --namespace galaxy --set ingress.enabled=false galaxy ./galaxy
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PriorityClass): unknown field "preemptionPolicy" in io.k8s.api.scheduling.v1beta1.PriorityClass
```

**Comment by pcm32** [comment]
Thanks, I haven't tried with Helm v3. On which commit are you regarding galay-helm?

Currently I'm using Helm v2.13.1, although this shouldn't explain the error, normally on the default namespace, and without ingresses as you are doing.

**Comment by nathanweeks** [comment]
The galaxy-helm commit is 1bbe7e51a076df501f5be35e3c838d3ee485bf01

I haven't tried Helm v2, but I would hope to avoid having to resort to doing that!

**Comment by pcm32** [comment]
I would suggest using helm v2, I think that here helm v3 is trying to outsmart API objects versioning and possibly making a wrong turn (in the client side validation), as I know positively that the object involved is available on the exact same version of k8s server that you're trying to use (we have been deploying it using helm v2 for the past few weeks on that version). If the API object wouldn't be available really on 1.14, then this wouldn't have spin up at all on GKE on our deployments, after initial server side validations.

**Comment by nathanweeks** [comment]
Skipping helm, I get an error when trying to create a simplified version of a PriorityClass resource with preemptionPolicy, even after downgrading kubectl to ensure there isn't an issue peculiar to the client:
```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
$ cat priorityclass-test.yaml 
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: test
value: -1000
preemptionPolicy: Never
globalDefault: false
$ ./kubectl create -f priorityclass-test.yaml 
error: error validating "priorityclass-test.yaml": error validating data: ValidationError(PriorityClass): unknown field "preemptionPolicy" in io.k8s.api.scheduling.v1beta1.PriorityClass; if you choose to ignore these errors, turn validation off with --validate=false
```

Setting `--validate=false` allows the PriorityClass to be created---but seemingly without a preemptionPolicy defined:
```
$ ./kubectl create --validate=false -f priorityclass-test.yaml
priorityclass.scheduling.k8s.io/test created
$ kubectl describe priorityclass.scheduling.k8s.io/test
Name:           test
Value:          -1000
GlobalDefault:  false
Description:    
Annotations:    <none>
Events:         <none>
```

**Comment by almahmoud** [comment]
Unfortunately, last week when I tried deploying on a GKE 1.14 cluster, I got the same error. 
After upgrading the cluster to 1.15, the error went away. I am not sure how this was working for you in the past @pcm32 (maybe Helm 2 is just deploying as with validate off?), but I think we might have to mark the charts as 1.15+ unless we can think of a way to make them backwards compatible again, but I am not sure how easy that will be

**Comment by pcm32** [comment]
Weird, I guess that explains it, maybe helm v2 is working with validate off by default.

**Comment by almahmoud** [comment]
Closing this in favor of https://github.com/galaxyproject/galaxy-helm/issues/242 where we can resolve this issue more permanently
