### ISSUE TITLE
Installation of tools via ephemeris produces a timeout

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#108]
Installing tools via ephemeris using:

```
shed-tools install --install_resolver_dependencies \
    --toolsfile $lock_file \
    --galaxy $GALAXY_INSTANCE \
    --api_key $API_KEY 2>&1 | tee -a $name.log
```

produces the following time outs:

```
18:07:05 (12/46) Installing repository cutadapt from lparsons to section "RNA-Seq" at revision 660cffd8d92a (TRT: 0:12:18.154861)
18:07:50 Timeout during install of cutadapt, extending wait to 1h
18:07:50 	repository cutadapt installed successfully (in 0:01:20.257473) at revision 660cffd8d92a
18:07:50 (13/46) Installing repository cutadapt from lparsons to section "RNA-Seq" at revision e4691e1589d3 (TRT: 0:13:38.412541)
18:09:23 Timeout during install of cutadapt, extending wait to 1h
18:09:23 	repository cutadapt installed successfully (in 0:01:10.167707) at revision e4691e1589d3
18:09:23 (14/46) Installing repository multiqc from iuc to section "RNA-Seq" at revision 3d93dd18d9f8 (TRT: 0:14:48.580530)
18:10:08 Timeout during install of multiqc, extending wait to 1h
18:10:17 	repository multiqc installed successfully (in 0:01:19.812481) at revision 3d93dd18d9f8
18:10:17 (15/46) Installing repository multiqc from iuc to section "RNA-Seq" at revision b2f1f75d49c4 (TRT: 0:16:08.393306)
```

They seem to be harmless, but I wonder if this is somehow related to the lack of an nginx setup at the front?

The tools on the tool panel don't look good though (and we use this same setup to provision other Galaxy spin ups), but maybe that is because the process is still on-going?

Is it harmful to have more than a single web handler when requesting these installations? Maybe I should drop the `--install_resolver_dependencies` flag in this case? I know that, based on the logs, the conda packages are not being installed as expected. I will try tools once they are all installed and see whether they work out of the box with the mulled containers as I expect.

**Comment by almahmoud** [comment]
Conda dependencies are turned off. When a tool is invoked, a biocontainer name is generated based on tool dependencies. Re the installation, to my understanding, installing a tool will get the wrapper and tool scripts from the toolshed to the `shed_tools` directory and update the `shed_tool_conf`, both of which are on the NFS and shared among all the running handlers. I believe Galaxy also has watchers that detect changes in the `tool_conf` to reload the toolbox, which should update all handlers.

**Comment by pcm32** [comment]
Well, ephemeris just calls the underlying REST API, so I would assume they are equivalent. Anyways, besides taking a long while to install (229 + 46 + 19 tools, considering different versions, in total) from the toolshed, seems to be fine.

**Comment by pcm32** [comment]
...and tools are working correctly :-)

**Comment by almahmoud** [comment]
Regarding:
> taking a long while to install

If you have a pre-boot list of what tools you'd want, you could theoretically just add them to the `tool_conf.xml` in values to load the tools from the toolshed repositories on the CVMFS rather than fetch them from the toolshed onto the NFS.

**Comment by pcm32** [comment]
ahhh, so the CVMFS mount has all the toolshed tools? What about the database part of the installation? or is that in the CVMFS as well? Thanks!

**Comment by pcm32** [comment]
Ok, I think that the refresh between web handlers of installed tools is not working great (this might be an underlying issue with Galaxy, as I think I have seen this on my HPC installations). Basically, if I open a workflow that uses many of the tools installed, every time I open it for edition, its telling me that different tools are missing. So I'm guessing that certain web handlers are spotting certain tools and missing others.

**Comment by afgane** [comment]
You should be able to skip `--install_resolver_dependencies` if you have corresponding containers for the tools because anything that gets built is not actually used/available to the tools when they run. That should speed up the installation significantly.

**Comment by almahmoud** [comment]
> What about the database part of the installation? or is that in the CVMFS as well? Thanks!

We don't have an install database and the tools are being loaded without it, specifically, you'll see the following message in the logs:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/toolbox/base.py#L710


> ahhh, so the CVMFS mount has all the toolshed tools? I thought it was only a selection (say IUC tools). 

It's not only IUC. At least all the tools on Main should be on the CVMFS `main.galaxyproject.org` repository, and for a rough idea from a list I had from a few months ago, there are at least tools from the following repos:
```
devteam
bhaas
pjbriggs
guru-ananda
crs4
aaronquinlan
iuc
pcingola
bgruening
rnateam
tyty
peterjc
nick
gregory-minevich
anton
lparsons
biopython
guerler
arkarachai-fungtammasan
boris
blankenberg
pcingola.old.dan
miller-lab
nate
sauria
jjohnson
iyad
nml
engineson
nilesh
wolma
greg
mvdbeek
```

**Comment by pcm32** [comment]
...mmm.. our ebi-gxa from the main toolshed doesn't seem to be there. How do we add it there?

**Comment by almahmoud** [comment]
You’d have to PR to https://github.com/galaxyproject/usegalaxy-tools in usegalaxy.org section.
If you message me a list of tools and tool versions, I can also do it for you if you’d like.

**Comment by pcm32** [comment]
Ok, removing the `--install_resolver_dependencies` makes it faster, like 10 minutes for 46 tools. I'll investigate adding our tools to usegalaxy-tools as suggested by @almahmoud. Thanks for all the feedback guys!
