### ISSUE TITLE
Quast HTML output

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy-helm#118]
Quast is actually the one with the bad output.
Alex O found the issue a few weeks ago but we never got back to it.
I published a history. If you click on the "visualize" (eye) button on the HTML output of Quast, it's just printed not rendered:
https://htmltest.cloudve.org/initial/galaxy/u/alexm/h/quast-output

I added Quast to `sanitize_whitelist.txt` but it didn't fix it

**Comment by dannon** [comment]
To update this ticket, Quast reports seem to work fine when added to the sanitize whitelist locally.  My entry looks like:
`
toolshed.g2.bx.psu.edu/repos/iuc/quast/quast/5.0.2+galaxy1
`

Might be an issue in how this is propagated through the helm wizardry?

**Comment by almahmoud** [comment]
Figured out the issue as to why it wasn't propagating. Problem with changing configmaps that are mutable via Rancher/Cloudman is that it will change the readonly one but because the mutable is already there, it won't update it (`-n` flag in: https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/templates/_helpers.tpl#L80). We however can't have upgrades re-copy blindly, because if you had a change made from admin UI, it will be overwritten by the configmap upgrade.
I'd therefore suggest we remove mutable configs from Cloudman upgrade list, so users are not surprised by the change not taking effect, because the upgrade will not actually change the live version, just the configmap and not propagate to Galaxy. I can also add a note in the README of the chart then that mutable configs can only be changed via configmap the first time, after which they need to either be modified manually (i.e. exec into one of the handlers and manually change file on the NFS), or do it through UI.
Alternatively, we could add some merge logic to combine the files, although this might open a can of worms that we don't want to deal with rn imo.

**Comment by almahmoud** [comment]
Closing this, since it's not a Quast-specific issue, in favor of https://github.com/galaxyproject/galaxy-helm/issues/123
