### ISSUE TITLE
Make a release that is backwards compatible until k8s 1.13 and then move on to remove deprecations

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#130]
You might have seen that GKE is moving to k8s 1.16 which will drop a number of deprecated API object versions. We should merge the easiest PRs currently waiting, make a release that we can point to for k8s versions before 1.16, and start moving on to be ahead of the change on GKE.

> Hello Google Kubernetes Engine Customer,
> 
> We are writing to let you know that upstream Kubernetes open source is removing deprecated APIs in v1.16. Once Google Kubernetes Engine (GKE) upgrades your clusters to v1.16, you will no longer be able to use the deprecated API versions.
> 
> What do I need to know?
> 
> GKE will gradually upgrade clusters to Kubernetes v1.16:
> 
> clusters subscribed to the regular release channel will begin upgrades on or after April 9, 2020
> clusters subscribed to the stable release channel and non-release-channel clusters will be upgraded later this year; a reminder will be sent before these clusters are upgraded to v1.16
> For more control over when an auto-upgrade can occur (or must not occur), you can configure maintenance windows and exclusions.
> 
> As the Kubernetes API evolves they get periodically reorganized or upgraded. When APIs evolve, the old API is deprecated and eventually removed.
> 
> The v1.16 release won’t serve deprecated versions of the following APIs, in favor of newer and more stable API versions:
> 
> DaemonSet versions extensions/v1beta and apps/v1beta2 are deprecated
> 
> use apps/v1, available since Kubernetes 1.9
> Deployment versions extensions/v1beta1, apps/v1beta1, and apps/v1beta2 are deprecated
> 
> use apps/v1, available since Kubernetes 1.9
> ReplicaSet versions extensions/v1beta1, apps/v1beta1, and apps/v1beta2 are deprecated
> 
> use apps/v1, available since Kubernetes 1.9
> StatefulSet versions apps/v1beta1 and apps/v1beta2 are deprecated
> 
> use apps/v1, available since Kubernetes 1.9
> NetworkPolicy version extensions/v1beta1 is deprecated
> 
> use networking.k8s.io/v1, available since Kubernetes 1.8
> PodSecurityPolicy version extensions/v1beta1 is deprecated
> 
> use policy/v1beta1, available since Kubernetes 1.10
> As of Kubernetes 1.16, API clients will no longer be able to use the deprecated API versions, and manifests using those versions will no longer be able to be applied.
> 
> Note that all previously persisted objects remain functional. They can be read and updated via the new API versions, before and after the Kubernetes 1.16 upgrade.
> 
> What do I need to do?
> 
> Migrate to use the current API versions before your clusters are upgraded to Kubernetes v1.16 to ensure your API clients and resource manifests can access and update API resources without interruption. More information is available from the Kubernetes project.

**Comment by almahmoud** [comment]
To succinctly capture update on this from meeting, I believe the decision is that we're going to parametrize the chart to change API versions for different k8s versions, until changes are so backwards incompatible that it becomes too much of a burden to maintain old k8s versions. At that point we'll revisit, but likely release a final version for old k8s and continue development only for newer versions. I believe that can happen via a value eg: `((.Values.k8s_version}}`. @pcm32 would you be able to add that logic?

Also to capture gitter conversation with @luke-c-sargent, this is going to relate to probes in that 1.16 offers `startup probes` so the current tentative plan is to add conditional logic for those probes as well
