### ISSUE TITLE
The initdb secret cannot be created

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy-helm#139]
Hi,
when trying to install galaxy-helm for the first time on Kubernetes 1.18 bare-metal, I get the following message: `Secret "galaxy-galaxy-initdb" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
Can you either look into that or provide another way to initialize postgresql?
Thanks!

PS: the `init2 restore` file is extremely long, when using `kubectl apply` it ends up into the annotation.

**Comment by cyrilcros** [comment]
So, a few comments:

- I ended up extracting and gzipping the database dump in `init2` , and I put into a folder `galaxy/files/docker-entrypoint-initdb.d`  which means the size is acceptable and the dump is applied according to the `initdb` notes for the Bitnami image for postgresql.

- I got rid of init1 and replaced it with some of the PostgreSQL `values.yaml` , you can create the galaxy user / password / db that way. I am not sure why you would want a different user, or then you should allow the possibility to connect to an external database. The `secret-initdb` Secret is not needed then.

- The `ingress.yaml` has likely some infinite redirect loop for the default path '/' due to this line: `nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^({{ .Values.ingress.path }})$ {{ .Values.ingress.path }}/ redirect;`; users should be able to use their own annotations.

- The use of `preemptionPolicy: Never`  for `priorityclass-job.yaml` is annoying, that should be an option to change in the chart.

**Comment by nuwang** [comment]
@cyrilcros Which version of etcd are you using? Newer versions of etcd support 1MB keys, so my first guess is that this is tied to the etcd version.

The reason for having this init script is to make startup faster, as the Galaxy migrate process takes a long time by default. The latest version of Galaxy will obviate the need for this init script completely, as it can create the initial database state without running each migration in sequence, and thus, offers pretty much similar performance. Therefore, our plan is to get rid of this initscript once we switch to Galaxy 20.05, so going forward, this will become a non-issue.

Users can currently define their own annotations, but they cannot override this particular annotation as it's required for uwsgi to correctly serve the request. Has this caused a problem?

Can you clarify your usage scenario wrt to `preemptionPolicy`? You can override the default preemption policy with a custom one by changing this: https://github.com/galaxyproject/galaxy-helm/blob/1bbe7e51a076df501f5be35e3c838d3ee485bf01/galaxy/values.yaml#L192

**Comment by cyrilcros** [comment]
Thank you for your very helpful reply! I will be closing this.

- I used k8s.gcr.io/etcd:3.4.3-0 from kubeadm, Kubernetes v1.18
- If this migration is going away, this is a non issue. Thanks! I currently have the galaxy / galaxy-cvmfs running on my cluster after a few edits to the templates, when your 20.05 version is out I will switch to it.
- That annotation isn't a big issue, I can always edit the templates if needed.
- The `preemptionPolicy: Never` was annoying for a cluster that doesn't have it enabled, I missed the fact that the galaxy configuration file also controls some aspects of the Kubernetes configuration. Problem solved.
