### ISSUE TITLE
Need to use a service account or be able to specify one

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy-helm#150]
Currently, we are using the default service_account. Being able to specify an alternative account would be more secure.

**Comment by almahmoud** [comment]
+1, and it should be a very straightforward thing to do (mimicking this https://github.com/CloudVE/cloudlaunch-helm/blob/414a63652af94cb49abeca14773d6437cd665dd0/cloudlaunchserver/templates/cl-server-deployment.yaml#L31)

One question is, should default still be the service account launching the chart as it is now, or should we deploy our own restricted SA as a default if none are specified?
