### ISSUE TITLE
CVMFS disabled still leaves breaking config in galaxy.yml

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#174]
Starting the helm chart with CVMFS disabled still leaves (with chart version 3.20 to 3.4.2 at least) a config map with galaxy.yml values that break because the point to the expected CVMFS path. It used to be I think that giving a galaxy.yml file in the configs of helm used to replace the galaxy.yml in the config map, but now apparently there is a merge going on. The deployment fails with:

```
No handlers could be found for logger "__main__"
Traceback (most recent call last):
  File "/galaxy/server/scripts/galaxy-main", line 299, in <module>
    main()
  File "/galaxy/server/scripts/galaxy-main", line 295, in main
    app_loop(args, log)
  File "/galaxy/server/scripts/galaxy-main", line 142, in app_loop
    attach_to_pools=args.attach_to_pool,
  File "/galaxy/server/scripts/galaxy-main", line 108, in load_galaxy_app
    **kwds
  File "/galaxy/server/lib/galaxy/app.py", line 115, in __init__
    self._configure_tool_data_tables(from_shed_config=False)
  File "/galaxy/server/lib/galaxy/config/__init__.py", line 1077, in _configure_tool_data_tables
    config_filename=self.config.tool_data_table_config_path)
  File "/galaxy/server/lib/galaxy/tools/data/__init__.py", line 80, in __init__
    self.load_from_config_file(single_config_filename, self.tool_data_path, from_shed_config=False)
  File "/galaxy/server/lib/galaxy/tools/data/__init__.py", line 117, in load_from_config_file
    tree = util.parse_xml(filename)
  File "/galaxy/server/lib/galaxy/util/__init__.py", line 236, in parse_xml
    root = tree.parse(fname, parser=ElementTree.XMLParser(target=DoctypeSafeCallbackTarget()))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/cvmfs/main.galaxyproject.org/config/shed_tool_data_table_conf.xml'
```

The only way to overcome this, without changing the chart version, is to make sure that the provided `galaxy.yml` overrides the values injected with CVMFS paths. I had to add the following to my local helm config:

```
configs:
  galaxy.yml:
    ...
    builds_file_path: "{{.Values.persistence.mountPath}}/tool-data/shared/ucsc/builds.txt"
    tool_data_table_config_path: "/galaxy/server/config/tool_data_table_conf.xml.sample"
```

that seems to fix it, but we need to check that CVMFS disabled works as expected. Also, not setting it explicitly (CVMFS to enabled: false) also tries to create the PVCs (and hence never starts).

**Comment by almahmoud** [comment]
When packaging with `scripts/helm_package` (which is what is used for our repository), `values-cvmfs.yaml` becomes `values.yaml`. Setting CVMFS to disabled doesn't change the rest of the values. I believe if you're using the packaged chart, to have a non-CVMFS values, you have to manually remove all values that use the CVMFS. There was an accidental paste that included build site from CVMFS on the normal `values.yaml` file, addressed in https://github.com/galaxyproject/galaxy-helm/pull/175

**Comment by pcm32** [comment]
Could we maybe then make two separate packages, with and without CVMFS? or this is only happening for older versions of the chart?

**Comment by almahmoud** [comment]
I would personally say we should probably revisit the packaging with CVMFS values thing altogether.
If possible, ideally we'd actually have the CVMFS bits conditional in the default YAML as I think you expected. (i.e. if CVMFS is enabled, the defaults from CVMFS are added to `galaxy.yml`, if not, they are ignored. I am not sure how straightforward that will be or if there are some specific blockers to why we can't do that.
@nuwang @afgane might be a good topic to talk about today.

**Comment by almahmoud** [comment]
@pcm32 When/if you have the time, please check whether the latest consolidated values file fixed all the problems you were experiencing here, and possibly close the issue if they are fixed?
I think the next release will be the first one dropping the `cvmfs-enabled` default packaging, so while we were packaging the `values-cvmfs.yaml` as `values.yaml` by default in the past, we will be packaging the actual `values.yaml` going forward.

**Comment by almahmoud** [comment]
This should be fixed now, please reopen if it comes up again.
