### ISSUE TITLE
Bug in the k8s runner configuration of extraVolume

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy-helm#207]
I noticed a pvc I was trying to mount as `/mnt/my-pvc` was fine in the main pods, but Kubernetes runners would see it as `’/mnt/my-pvc/\n’` and my scripts would fail.
In the `values.yaml`, this line https://github.com/galaxyproject/galaxy-helm/blob/d12395f121e2ff739b6ad74af54c4facb95ef582/galaxy/values.yaml#L211 is followed by a block conditional on `.Values.extraVolumes`. The new line should be removed at the end.
The line is https://github.com/galaxyproject/galaxy-helm/blob/d12395f121e2ff739b6ad74af54c4facb95ef582/galaxy/values.yaml#L214
Replace it by `{{- end -}}` with a dash

**Comment by nuwang** [comment]
Thanks for reporting this. It should be fixed in:
https://github.com/galaxyproject/galaxy-helm/issues/207
and
https://github.com/galaxyproject/galaxy/pull/11223

**Comment by cyrilcros** [comment]
Thanks @nuwang , I will close this. By the way, could you take another look at https://github.com/galaxyproject/galaxy-helm/issues/155 ? Helm 2 is now out of support (cf https://helm.sh/blog/helm-v2-deprecation-timeline/ ) and the out of sync `requirements.lock` prevents people from directly using this repository. I use the CloudVe `helm-charts` repo instead, but it can lag a bit.
