### ISSUE TITLE
Wrong postgresql repo location

### ISSUE THREAD

**Issue by viktoriaas** [galaxyproject/galaxy-helm#208]
Hi, 
I've tried to deploy helm galaxy chart and stumbled across a problem with postgresql dependency in `requirements.yaml`. 
The issue is that postgresql chart has been relocated to different repository and putting 
```
repository: https://charts.bitnami.com/bitnami
version: 10.2.4
```
in `requirements.yaml` fixed the dependency.

**Comment by nuwang** [comment]
@viktoriaas Thanks for reporting this. Work is being done to drop Helm 2 support, and we can include a fix for this along with it.

**Comment by nuwang** [comment]
@viktoriaas This is fixed in: https://github.com/galaxyproject/galaxy-helm/pull/216/. Let us know if you run into any further issues.
