### ISSUE TITLE
Problems with file uploading and downloading

### ISSUE THREAD

**Issue by viktoriaas** [galaxyproject/galaxy-helm#219]
Hi, 
I don't want to continue in #214 because this issue is different. We have a working Galaxy deployment and added our own tool.

**Problem 1**
When cvmfs is disabled, the PVCs related to them isn't created, right. However, they are later requested when uploading file to Galaxy. In the end, they are not used, the files are stored under _objects_ directory in `galaxy-pvc`. I don't understand why in [values.yaml job.xml](https://github.com/galaxyproject/galaxy-helm/blob/e9167da89481c6ba3db39bb75d524a315f6dae09/galaxy/values.yaml#L217) has both cvmfs PVCs specified, even when disabled. Maybe if these two were included only when cvmfs in **enabled** then the upload wouldn't fail on missing cvmfs pvc.

**Problem 2**
I've manually created cvmfs PVCs, then upload ended okay. When I wanted to view the results, 2 fastq files could be viewed and one txt couldn't. No result could be downloaded, outcome was `404 Not found`.

Here you can see that 2 subsequent queries for preview are different - one HTTP 200, another 404
```
192.168.150.245 - - [11/Feb/2021:14:48:23 +0000] "GET /datasets/9a55ed48fb2654dc/display/?preview=True HTTP/1.1" 200 74301 "https://el-galaxy.cerit-sc.cz/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
192.168.150.245 - - [11/Feb/2021:14:48:24 +0000] "GET /datasets/6260c2f98abaa914/display/?preview=True HTTP/1.1" 404 169 "https://el-galaxy.cerit-sc.cz/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
```

The 404 preview  save icon led to
```
https://XXX.cz/galaxy/datasets/133c49ca34a2f96a/display?to_ext=txt
```
but actually ended on
```
https://XXX.cz/galaxy/_x_accel_redirect/
```
which displayed 404.
I thought that nginx is not configured properly so I tried to change `ingress.path` but no change. I tried adding backslash after `location {{ template "galaxy.add_trailing_slash" .Values.ingress.path }}_x_accel_redirect` but didn't help. I tried a couple of other options.

[Galaxy docs talking about sending with nginx](https://docs.galaxyproject.org/en/master/admin/nginx.html#sending-files-with-nginx) say enabling `_x_accel_redirect` is good for the performance and therefore should be considered in production environments if you expect high traffic or machine loading. For testing purposes, I have disabled `_x_accel_redirect` both in `galaxy.yml` and in `configmap-nginx.yaml`. Then, viewing and downloading work. 

There might be a permission problem as mentioned in the section of the docs above. If nginx runs in own pod it does not necessarily have the rights to see Galaxy's `file_path` location.

**Comment by nuwang** [comment]
@almahmoud Problem 1 seems like a conditional bug after the values merge?

@viktoriaas Are you using the latest version of the chart?  There was a selector issue that was fixed that may result in what you're saying, but that has since been fixed.

**Comment by viktoriaas** [comment]
Yes, I am using the latest version. I cloned the master branch, the last log in the git log
```
commit e9167da89481c6ba3db39bb75d524a315f6dae09 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by nuwang** [comment]
@viktoriaas Can you try this in an incognito window or try a different browser? We've found that the browser caches this permanently if it happens even once.

**Comment by viktoriaas** [comment]
@nuwang what do you mean I should try? 

I treid brand new deployment and then opened galaxy url in different browser and in incognito window. Still demands cvmfs PVCs

**Comment by nuwang** [comment]
I was referring mainly to problem 2. Problem 1 appears to be a bug. The workaround you've implemented seems correct.

**Comment by viktoriaas** [comment]
I tried in incognito window but it still works only with added trailing slash in nginx conf. I've create a PR that could fix both issues I faced

**Comment by nuwang** [comment]
@natefoo Do you know why this trailing slash might be needed?
I don't see it in the usegalaxy playbook: https://github.com/galaxyproject/usegalaxy-playbook/blob/562e63fc944ba4541c522a3e845f83e4b41e64e4/env/main/templates/nginx/usegalaxy_staging.j2#L25
so that makes me suspect that something else is going on.

**Comment by viktoriaas** [comment]
@nuwang question:  I have tool path specified in the `tool_conf.xml` but the xml file does nto exist in the path yet. I deply Galaxy, everything is fine. Then, I add the file on specified location in PVC but the tool is still not visible on Galaxy web. I have also done `helm upgrade` but still nothing. What am I missing? I think it worked before

**Comment by viktoriaas** [comment]
With merge request, the issue is solved

**Comment by natefoo** [comment]
@nuwang what do you use for the [galaxy-side option](https://github.com/galaxyproject/usegalaxy-playbook/blob/cbb75f4dbbcc8f13cc5dcc986771fd2af5c05236/env/main/group_vars/all/galaxy_config_vars.yml#L153)?

**Comment by nuwang** [comment]
@natefoo Server side is almost the same as usegalaxy, except for the proxy prefix: https://github.com/galaxyproject/galaxy-helm/blob/21a4cfcad8e1e87cd6af6cd8b28b0a9a9d136e02/galaxy/values.yaml#L314

**Comment by nuwang** [comment]
@viktoriaas Do you have a trailing slash in your galaxy-config perhaps?

**Comment by viktoriaas** [comment]
No, my setup is exectly same as in galaxy docs.
`galaxy.yml` : `  nginx_x_accel_redirect_base: '/galaxy/_x_accel_redirect'`
`nginx.conf` : `location /galaxy/_x_accel_redirect/ {`
