### ISSUE TITLE
Redirect issue with oauth?

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy-helm#220]
Hi, with Galaxy v21.01, Helm Chart v3.9.4 I seem to see some issue with oauth. My URL is `https://galaxy.DOMAIN/galaxy/` and after authentication via Google Oauth I now get redirected to `https://galaxy.DOMAIN/galaxy/galaxy/#`. This is still a successfull auth, I just need to go back to `https://galaxy.DOMAIN/galaxy/`.
My `oidc_backends_config.xml` has the line `<redirect_uri>https://galaxy.DOMAIN/galaxy/authnz/google/callback</redirect_uri>` and matches what I have on the Google API console. I followed: https://galaxyproject.org/authnz/config/oidc/
I expect I can solve it by moving the redirect to `https://galaxy.DOMAIN/authnz/google/callback`, but it seems there was a change since 20.09....
My `values` file has been updated with the nginx proxy refactor: https://github.com/galaxyproject/galaxy-helm/blob/e9167da89481c6ba3db39bb75d524a315f6dae09/galaxy/values.yaml#L301

**Comment by nuwang** [comment]
I haven't tested this properly with 21.01 yet. Which image did you use? And it doesn't work for you only with 21.01 right?
@almahmoud Have you run into this?

**Comment by cyrilcros** [comment]
I am using `galaxy/galaxy-k8s:21.01` . 20.09 with the 3.8.4 Chart was fine.

**Comment by almahmoud** [comment]
I haven't tested 21.01 auth at all

**Comment by nuwang** [comment]
@cyrilcros Yes, the 21.01 build was most experimental and hasn't been tested. I've built and pushed a newer version of galaxy/galaxy-k8s:21.01. Can you try pulling it again and check whether it works?

**Comment by cyrilcros** [comment]
Hi, I checked the new image you made and it failed. I reconfirmed galaxy-k8s 20.09 is fine using the exact same Helm version and values apart from the `image.tag`. It isn't a big issue for me, just something to look out for while you develop 21.01.

**Comment by nuwang** [comment]
Ok, thanks for reporting on that. @dannon Do you know whether anything changed with auth that could trigger this?

**Comment by almahmoud** [comment]
There was a bug in Galaxy starting with 21.01 where OIDC login was broken. I made a fix that got backported a few months ago: https://github.com/galaxyproject/galaxy/pull/12161
