### ISSUE TITLE
Separate workflow from job handlers in values via `applyToWorkflow`

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy-helm#226]
The original chart was designed for 2 handlers (job and web), then a third workflow handler was later added, but the values have not been updated to be able to customize the workflow handler independently. For the most part, `applyToJob` still applies to both the Job handler and Workflow handler.

Things to do:
- [x] In [values.yaml](https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/values.yaml#L107) add `applyToWorkflow` wherever `applyToJob` and `applyToWeb` exist (including commented examples). Mimic the defaults to be the same as `applyToJob`
- [x] In [deployment-workflow.yaml](https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/templates/deployment-workflow.yaml) change all mentions of `applyToJob` to be `applyToWorkflow`
- [x] Test the values you added. Tip: create a tmp dir (eg: `mkdir my-tmp-dir`) then run `helm template ./galaxy-helm/galaxy --generate-name --output-dir ./my-tmp-dir` to generate templates. You can then compare the workflow template at `./my-tmp-dir/galaxy/templates/deployment-workflow.yaml` running first with `applyToWorkflow` in values being True then False, and check whether the behavior is what would be expected.

**Comment by ksuderman** [comment]
I can't self-assign this, but I will start working on it.
