### ISSUE TITLE
Favicon and logo paths are not right

### ISSUE THREAD

**Issue by viktoriaas** [galaxyproject/galaxy-helm#295]
Hi, 
current galaxy ingress values are mismatched. Original values for ingress are:
```
  path: /galaxy
  hosts:
    - host: ~
      paths:
        - path: "/galaxy"
```

This paths cause not displaying logo and favicon because the path in HTML source is `src=/static/favicon.png` . When I type that URL (`hostname.com/static/favicon.png`) I get  404 - default backend because ingress is configured for `galaxy`.

So I changed both paths in ingress for `\` which is fine and all logos are displayed. However, the galaxy canary ingress is not ready for empty path, `helm upgrade` throws an error:
```
Error: UPGRADE FAILED: cannot patch "galaxy-activity-canary" with kind Ingress: Ingress.extensions "galaxy-activity-canary" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "//api/users/": must not contain '//'
```

I fixed the issue by removing the `ingressPath` from canary ingress template but proper fix asking if `ingressPath` is empty would be required. 
```
          - path: /api/users/                                                   
          #- path: {{ $ingressPath }}/api/users/  
```

**Comment by almahmoud** [comment]
Nuwan's PR should fix the `//` issue.
Regarding the icon, you can fix this by changing `logo_src` in `galaxy.yml`: https://docs.galaxyproject.org/en/release_21.01/admin/config.html#logo-src

I will PR a new default in a sec
