### ISSUE TITLE
Remote files functionality missing and upgrade leads to DB issues

### ISSUE THREAD

**Issue by viktoriaas** [galaxyproject/galaxy-helm#299]
Hi, 
according to release notes Galaxy v21.01 presented the "Remote files" functionality (https://galaxyproject.org/news/2021-03-galaxy-release-21-01/#remote-files). 

How can I enable it? I suspect it has to do something with `file_sources_conf.yml.sample` (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/file_sources_conf.yml.sample). The file is present in `galaxy/server/config` but it doesn't do anything.

I tried to just copy the file in the directory, but without the `.sample` extension and redeploy web, job, nginx pods but `galaxy-db-init` is now failing with 
```
migrate.exceptions.VersionNotFoundError: "Database schema file with version 176 doesn't exist."
```

It might be related to #296. Again, I deleted everything and installed new galaxy. Then, I copied the file once again and updated the galaxy helm deployment but after that, I realized that `galaxy/server/config` is not a folder, which would be mounted on a PVC so redeploy has removed the copied file (without the `.sample` extension). Therefore, I don't know if there is any prepared way of utilizing the `Remote files` in helm galaxy.

**Comment by almahmoud** [comment]
If you want to inject a config file into `/galaxy/server/config`, you should be using the `configs` section of the helm chart.
If you have the file that you want saved from wherever you're running the helm command, you can do `helm upgrade --set-file configs."file_sources_conf\.yml"=/path/to/file/locally/file_sources.yml`
If you're trying to add a config manually to be persistent, you should add the configs on whatever persistent volume you're using. This will be under `/galaxy/server/database`. For configs that need to be write-able and persisted, we have `/galaxy/server/database/config` or `/galaxy/server/config/mutable` (they are the same directory, at two mountpaths).

Regarding the version error above, I don't think it's related to the upgrade. Perhaps try setting `--set image.pullPolicy=Always`, especially if you have a multi-node cluster, it might be that different nodes have different versions of the same tagged image (21.05 is not released yet, so the image is still being auto-built with every commit on the release branch). If that's not the case, I am not sure what else would cause the container to come up with a different image (the schema migration files are baked into the image, not injected by the chart, so for that error to happen, the init container must be using an older image than what had created the DB originally is my only guess unless I'm missing something)
