### ISSUE TITLE
create_db.sh throws exception with a seperate postgresql install

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy-helm#304]
Pastebin from the init db container: https://pastebin.com/apR2TvrV
Pastebin from SQL: https://pastebin.com/68LV3un3

Your postgresql operator works for me. However, when using https://github.com/bitnami/charts/tree/master/bitnami/postgresql I get errors during database creation....

Would it please be possible to get an option to purge everything in the database, before running `/galaxy/server/create_db.sh`?  If anything happens during install, the db init job will attempt to create the table over and over again. It would be best to clean the database fully before attempting to create anything. It could also be merely optional.

Alternatively, it could be much nicer to start from a SQL dump rather than going through the database init / migrations...

**Comment by almahmoud** [comment]
We could add a flag for that. I would personally prefer to keep the default as `false` as to not increase the possibility of accidental DB deletions, but having the option would definitely be a nice feature.
In the meantime, there are a few options to unblock you:
1) We have a branch for one of our funded collaborative projects `anvil` which has the `4.0.0` chart with the old `postgresql` dependency with the new v4 features. If you don't need some of the later additions from the past few weeks, and if you are running relatively transient instances and it's not a problem to run from a branch in the meantime, that would be an easy out-of-the box option.
2) You can create the Galaxy database separately, for example with by using an [init script](https://github.com/galaxyproject/galaxy-helm/blob/anvil/galaxy/files/conf.d/init1_dbobjects.sh) and pass it to your separate helm install for the bitnami postresql chart (eg [with `initdbScriptsSecret`](https://github.com/galaxyproject/galaxy-helm/blob/anvil/galaxy/values.yaml#L231)), and then run the Galaxy chart with `initJob.createDatabase=false` so it will expect the database to exist.

**Comment by cyrilcros** [comment]
Closing this; for now things are working and I think it has the same cause as #303 (restarted jobs)...
