### ISSUE TITLE
Add support for CVMFS CSI

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy-helm#31]
Given there can be many job containers running on a given K8S node, it does not seem to make sense for each of them to have a CVMFS client for accessing Galaxy's reference data. This would complicate the job container plus lead to very redundant network traffic where each container is retrieving its own copy of the data.

It seems CVMFS CSI is intended to solve this issue by creating a volume on a node and making it available to the containers running on the node: https://gitlab.cern.ch/cloud-infrastructure/cvmfs-csi

Has anyone worked with this perhaps? Or some other CSI implementation as a concept? Is my understanding captured above even correct?

**Comment by pcm32** [comment]
I haven't tried it, but the reasoning of avoiding direct CVMFS mounts per container and deal with this centrally on the setup, having it as a single read-many PV dynamically provisioned via StorageClass, sounds adequate.

**Comment by nuwang** [comment]
CVMFS-CSI has been integrated, so closing.
