### ISSUE TITLE
Suggestion about galaxy/ingress.yaml

### ISSUE THREAD

**Issue by mshaikh786** [galaxyproject/galaxy-helm#368]
At times one may need to dedicate an `ingressclass` and corresponding ingress-controller. In the `galaxy/templates/ingress.yaml`, the ingressClassName is set to "nginx" which is usually the default class name when an ingress-controller is deployed. Would it be better to set the same variable as is set in the `galaxy/templates/ingress-activity-canary.yaml`, i.e.
`ingressClassName: {{ .Values.ingress.ingressClassName }}`

**Comment by nuwang** [comment]
Thanks for reporting this. This is a bug and should be fixed.
