### ISSUE TITLE
helm install is successful but getting an error on landing page

### ISSUE THREAD

**Issue by mshaikh786** [galaxyproject/galaxy-helm#369]
Hi, 
I installed the helm chart successfully, with a few minor modifications. These changes were in ingress-class and the storage classes which are nfs for PVCs postgresql and galaxy-pvc. 
The chart release is 4.0.0. 
On the landing page of Galaxy, I get the following error:
`An error occurred
An error occurred while updating information with the server. Please contact a Galaxy administrator if the problem persists.
 
The following information can assist the developers in finding the source of the error:

{
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
  "onLine": true,
  "version": "21.05",
  "xhr": {
    "readyState": 4,
    "responseText": "{\"err_msg\": \"History is not accessible by user\", \"err_code\": 403002}",
    "responseJSON": {
      "err_msg": "History is not accessible by user",
      "err_code": 403002
    },
    "status": 403,
    "statusText": "Forbidden"
  },
  "options": {
    "parse": true,
    "data": "keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
    "emulateHTTP": false,
    "emulateJSON": false,
    "textStatus": "error",
    "errorThrown": "Forbidden"
  },
  "url": "http://galaxy.kaust.local/galaxy/galaxy/api/histories/12f072e1c95db54c?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
  "model": {
    "model_class": "History",
    "id": "12f072e1c95db54c",
    "name": "Unnamed history",
    "state": "new",
    "deleted": false,
    "contents_active": {
      "deleted": 0,
      "hidden": 0,
      "active": 0
    },
    "contents_states": {},
    "update_time": "2022-07-31T11:18:32.727Z",
    "contents_url": "/galaxy/api/histories/12f072e1c95db54c/contents",
    "annotation": null,
    "size": 0,
    "username_and_slug": null,
    "genome_build": "?",
    "user_id": null,
    "url": "/galaxy/api/histories/12f072e1c95db54c",
    "slug": null,
    "create_time": "2022-07-31T11:18:32.727Z",
    "importable": false,
    "hid_counter": 1,
    "purged": false,
    "published": false,
    "tags": [],
    "nice_size": "(empty)"
  },
  "user": {
    "id": null,
    "username": "(anonymous user)",
    "total_disk_usage": 0,
    "nice_total_disk_usage": "0 bytes",
    "quota_percent": null,
    "is_admin": false,
    "preferences": {}
  }
}
`
Any help and guidance to identify and fix this issue will be highly appreciated.

**Comment by nuwang** [comment]
The url has galaxy repeated twice, is that intentional? `http://galaxy.kaust.local/galaxy/galaxy/api/histories/12f072e1c95db54c?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter"`

Can you post a screenshot?

**Comment by mshaikh786** [comment]
Thanks @nuwang for prompt reply. 
I am unable to reproduce this issue anymore. All I did was reinstall the helm chart for the ingress controller I was using and then a new galaxy chart. Can't pinpoint what was different before. We can close this issue for now. Thanks for your assistance.
