### ISSUE TITLE
admin.email isn't added to galaxy_conf.admin_users

### ISSUE THREAD

**Issue by ilveroluca** [galaxyproject/galaxy-helm#38]
Using the `galaxy-stable` chart version 2.0.2.  When I configure a new user for my deployment through the `admin:` values (`username`, `email`, etc.) it doesn't get added to the `galaxy_conf.admin_users:` list.  I would expect this to happen automatically since the new user account is configured in a section called `admin` :-)

**Comment by pcm32** [comment]
I think that currently one needs to repeat the setting under:

```
galaxy_conf:
   admin_users: "list of emails for admins"
```

but is true that ideally setting admin.email should fill that other variable (although I'm not sure how to do that at the helm chart level).

**Comment by nuwang** [comment]
Closing because this is handled differently in latest chart version.
