### ISSUE TITLE
On Helm upgrade, Galaxy default tools don't get updated from a new galaxy container

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#418]
On subsequent runs of `helm upgrade...` of the chart, when the galaxy image changes, the default tools in `/galaxy/server/database/tools` don't get updated from the newer ones in the container.

Also, there is a repeated `/galaxy/server/database/tools/tools` directory with the same default tools again.

Should this be added in the init-mounts perhaps?

**Comment by pcm32** [comment]
if you point me to where it needs to happen I could attempt a PR, thanks.

**Comment by nuwang** [comment]
On startup, the Galaxy container copies the tools directory from the container into the tools folder:
https://github.com/galaxyproject/galaxy-helm/blob/d5d43d19c38397963e4f659bd9e486ca737ecbfa/galaxy/templates/_helpers.tpl#L164

I'm guessing this is a matter of a missing trailing "/", and the nested tools directory contains the newer files?

**Comment by ksuderman** [comment]
I think that is exactly what is happening; since a directory is being copied (`cp -r`) a new `tools` directory is being created inside the existing `tools/` directory.  Another solution would be to remove the `/tools` from `{{ .Values.persistence.mountPath}}`

**Comment by pcm32** [comment]
Cool, thanks for finding and addressing this!
