### ISSUE TITLE
CVMFS alien cache name mismatch

### ISSUE THREAD

**Issue by ksuderman** [galaxyproject/galaxy-helm#437]
We seem to have a bit of a mismatch in cvmfs cache name handling. The upstream chart uses [cvmfs-alien-cache](https://github.com/cvmfs-contrib/cvmfs-csi/blob/f1b4983caeb767ea85f8b041ac1ab284b4e9251f/deployments/helm/cvmfs-csi/values.yaml#L47)

And out chart uses [{{ .Release.Name }}-cvmfs-alien-cache-pvc](https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/a75a195396710bfc50dab3fb227330dea3a0c3a2/galaxy-cvmfs-csi/values.yaml#L36).

The mismatch causes the pvc name we create to mismatch the name expected by the daemonset. It would be better if we just used the nested chart's values, and if they are not defined, fallback to defaults.

**Comment by nuwang** [comment]
Makes sense. Even if multiple instances of the chart use the same alien cache, that should probably be ok. This is all such a mess because helm doesn't allow computed variables to be passed to included charts unless the included chart explicitly templates it. Badly breaks encapsulation.
