### ISSUE TITLE
Crashes without Refdata on CVMFS

### ISSUE THREAD

**Issue by mapk-amazon** [galaxyproject/galaxy-helm#439]
I currently try to deploy the helm chart without reference data.  When I do, https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/templates/hook-cvmfs-fix.yaml this hook starts up and continues to wait for some cvmfs pods (ironically to kill them). As there is no pod, it runs indefinitely.

```
refdata.enabled: false
refdata.type: s3sci
s3csi.deploy: false
cvmfs.deploy: false
cvmfs.enabled: false
```

*Expected behaviour*:
If no cvmfs is used, then the pod for fixing cvmfs does not run. _Alternatively_ after no pod is found for 1-2 minutes, the pod finishes up.

Thank you!

**Comment by ksuderman** [comment]
Thanks for the report. That was a hack we introduced to work around a problem with the CVMFS CSI driver and is hopefully no longer needed.  We should either:
1. Remove the `hook-cvmfs-fix.yaml` template (#441), or
2. Add a guard so the hook only executes when `refdata.enabled = true` and `refdata.type = cvmfs` (#440)
