### ISSUE TITLE
Building Galaxy Interactive Environment with Kubernetes on my own server

### ISSUE THREAD

**Issue by lizhi16** [galaxyproject/galaxy-helm#46]
I am trying to deploy the galaxy:19.05 with kubernetes following this project And it works.

But after setting the interactive environment following with https://docs.galaxyproject.org/en/master/admin/special_topics/interactive_environments.html, an error shows up when I tried to use the GIEs on the website.

error: GIEs are a fairly complex deployment and sometimes need maintenance. It seems that at the moment they are not launching, we are investigating.

I think it may because the sshfs didn’t be set in the right way, but I don’t know how to set it in the correct container (there was a series of containers running the galaxy together).

Would anybody know how to solve this problem? Thanks so much!

**Comment by pcm32** [comment]
Hi @lizhi16, AFAIK, there is no support yet for Interactive Environments on Kubernetes. It would have to be implemented. Currently IE rely heavily on talking to the docker engine directly, and what would be needed would something to adapt it to talk to Kubernetes. I started something some months ago, but haven't had the chance to finish it.

**Comment by afgane** [comment]
Also of relevance is the (currently open) InteractiveTools PR (https://github.com/galaxyproject/galaxy/pull/7494), which is supposedly likely to have support for Kubernetes by the time it gets merged, and arguably looks like a better path going forward.

**Comment by pcm32** [comment]
Yes, InteractiveTools seem much easier to integrate than interactive environments!

**Comment by lizhi16** [comment]
@afgane Thanks for your reply. But I'm sorry, I don't get what is the InteractiveTools PR. Is that the tools listed in the left bar of the galaxy webpage? Or it is tool similar to the Interactive Environments and can make users interactive with their data? Thank you!

**Comment by nuwang** [comment]
@lizhi16 At present, neither interactive environments nor its successor interactive tools are supported by the helm chart. However, this will be worked on in the first half of next year.
