### ISSUE TITLE
Option to set custom container image repositories for init containers

### ISSUE THREAD

**Issue by Slushy-seg** [galaxyproject/galaxy-helm#499]
The container name and tag can be customized for ngix and galaxy, e.g. through `nginx.image.tag` and `nginx.image.repository`. For init containers, the same parameters should exists. Currently hard coded to alpine:3.16.

```
      initContainers:
        - name: {{ .Chart.Name }}-wait-postgres
          image: alpine:3.16
```
```
        - name: {{ .Chart.Name }}-init-cloud-repo
          image: alpine:3.16
```
and so on.

**Comment by nuwang** [comment]
There's an extraInitContainers option that allows you to specify your own init containers: https://github.com/galaxyproject/galaxy-helm/blob/59c68b17210dcc7dac99f9236916ac89c39b7429/galaxy/values.yaml#L242
Would that be sufficient for your use case? If not, can you describe it in greater detail?

**Comment by Slushy-seg** [comment]
Thanks. I don't necessarily want to specify additional init containers. For my use case, I would like to specify the container image used for the default init containers. The reason is, that I'd like to have them pulled from my private repository.

**Comment by nuwang** [comment]
Right, that makes sense. We should add this in.
