### ISSUE TITLE
403 error minikube local deployment with galaxy-stable-phenomenal-18.01-minikube.yaml

### ISSUE THREAD

**Issue by jianlianggao** [galaxyproject/galaxy-helm#51]
[logs-from-galaxy-k8s-in-f1-galaxy-stable-788f4fb5f8-vgn75.txt](https://github.com/galaxyproject/galaxy-helm/files/3511774/logs-from-galaxy-k8s-in-f1-galaxy-stable-788f4fb5f8-vgn75.txt)

Hi all,

I used galaxy-stable-phenomenal-18.01-minikube.yaml and helm to deploy galaxy-k8s on my Windows 10 computer. helm install -f galaxy-stable-phenomenal-18.01-minikube.yaml --version 1.5.5 galaxy-helm-repo/galaxy-stable

The created pods ran on local cluster. But couldn't be connected. Log file is attached.

Any idea what has gone wrong? Many thanks.

**Comment by nuwang** [comment]
@jianlianggao That values file is from an older version of the chart. Have you tried the latest version?
