### ISSUE TITLE
using kubernetes build galaxy error

### ISSUE THREAD

**Issue by huster16** [galaxyproject/galaxy-helm#65]
1. when I use kubernetes 1.15 or 1.14 to build the galaxy, I meet an error:
Error: secrets "galaxy-galaxy-db-password" is forbidden: User "system:serviceaccount:kube-system:default" cannot delete resource "secrets" in API group "" in the namespace "default"

**Comment by almahmoud** [comment]
I have not seen that error before, but can certainly help you debug if you give us a few more details. A good place to start is helping us replicate your set-up to either figure out what was going wrong, or help us find a bug if the problem stems from the chart.
First of all, what environment are you running in? Eg: Is it a local kubernetes cluster (if so, on what OS, and is it using minikube, docker-for-Mac, etc...), or a commercial managed cluster (such as GKE, EKS, AKS, etc), or a Rancher cluster, or a different set-up? Also, did you change anything in the kubernetes cluster before running galaxy? And did you have any other charts or k8s resources running on the cluster, or was it new?
Second of all, what helm version are you running?
Finally, are you changing any values or running with the default minimal values?

**Comment by huster16** [comment]
> I have not seen that error before, but can certainly help you debug if you give us a few more details. A good place to start is helping us replicate your set-up to either figure out what was going wrong, or help us find a bug if the problem stems from the chart.
> First of all, what environment are you running in? Eg: Is it a local kubernetes cluster (if so, on what OS, and is it using minikube, docker-for-Mac, etc...), or a commercial managed cluster (such as GKE, EKS, AKS, etc), or a Rancher cluster, or a different set-up? Also, did you change anything in the kubernetes cluster before running galaxy? And did you have any other charts or k8s resources running on the cluster, or was it new?
> Second of all, what helm version are you running?
> Finally, are you changing any values or running with the default minimal values?

Thank you so much. I will describe all the details and building process:
I run the Kubernetes on two virtual machines, and the configurations of them are the following:
```
OS: CentOS 7.6
Kernel: 3.10.0-1062.el7.x86_64
Docker Version: docker-ce 18.03
CPU core: 2
Memory: 4G
Disk: 100G
```

And I don't use minikube, here is my process to build kubernetes:
**Environment **
```
master  192.168.68.10   CentOS 7.6 
node01  192.168.68.11   CentOS 7.6
```

**Configurations**

```
# systemctl stop firewalld
# systemctl disable firewalld
# update-alternatives --set iptables /usr/sbin/iptables-legacy
```

**Install kubeadm、kubelet、kubectl*
```
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

# Set SELinux in permissive mode (effectively disabling it)
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config  # 建议改成disabled

yum install -y kubelet-1.15.3 kubeadm-1.15.3 kubectl-1.15.3 --disableexcludes=kubernetes

systemctl enable --now kubelet
```

**Config Networking**
```
cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1 
EOF
sysctl --system
modprobe br_netfilter
```

**Set Hostname**
```
# master
echo "127.0.0.1   master" >> /etc/hosts
hostnamectl set-hostname master

# node01
echo "127.0.0.1   node01" >> /etc/hosts
hostnamectl set-hostname node01
```

**Deploy Master Node**
`kubeadm init --pod-network-cidr=10.244.0.0/16    # using flannel`

```
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`

**Config Node1**
```
# node01
kubeadm join --token <token> <control-plane-host>:<control-plane-port> --discovery-token-ca-cert-hash sha256:<hash>
```

**After these steps, we follow the instructions of the Galaxy and change nothing.**

**Comment by huster16** [comment]
@almahmoud And in the same environments, I met another error when I used the Kubernetes version 1.16:

```
[root@localhost galaxy]# helm install --name galaxy .
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```
And I try to use the minikube to deploy the Kubernetes, I also met this error.
```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

**Comment by nuwang** [comment]
@huster16 Has this issue been resolved? Did you try the latest version of the chart, I think the StatefulSet issue may have been resolved with that.
